const GET_REPORTS = "GET_REPORTS";
const GET_REPORT = "GET_REPORT";
const GET_METRICS = "GET_METRICS";

const ERR_REPORTS = "ERR_REPORTS";
const ERR_REPORT = "ERR_REPORT";
const ERR_METRICS = "ERR_METRICS";

export {
    GET_REPORTS,
    GET_REPORT,
    GET_METRICS,
    ERR_REPORTS,
    ERR_REPORT,
    ERR_METRICS
}